/// Maps ISO 4217 currency codes to human-readable label: flag + code + name + country.
class CurrencyNames {
  static const Map<String, String> _names = {
    'IDR': 'IDR — Rupiah (Indonesia)',
    'USD': 'USD — US Dollar (United States)',
    'EUR': 'EUR — Euro (European Union)',
    'GBP': 'GBP — British Pound (United Kingdom)',
    'JPY': 'JPY — Japanese Yen (Japan)',
    'CNY': 'CNY — Chinese Yuan (China)',
    'SGD': 'SGD — Singapore Dollar (Singapore)',
    'MYR': 'MYR — Malaysian Ringgit (Malaysia)',
    'THB': 'THB — Thai Baht (Thailand)',
    'KRW': 'KRW — South Korean Won (South Korea)',
    'INR': 'INR — Indian Rupee (India)',
    'AUD': 'AUD — Australian Dollar (Australia)',
    'CAD': 'CAD — Canadian Dollar (Canada)',
    'CHF': 'CHF — Swiss Franc (Switzerland)',
    'SAR': 'SAR — Saudi Riyal (Saudi Arabia)',
    'BND': 'BND — Brunei Dollar (Brunei)',
    'VND': 'VND — Vietnamese Dong (Vietnam)',
    'AED': 'AED — UAE Dirham (United Arab Emirates)',
    'AFN': 'AFN — Afghan Afghani (Afghanistan)',
    'ALL': 'ALL — Albanian Lek (Albania)',
    'AMD': 'AMD — Armenian Dram (Armenia)',
    'ANG': 'ANG — Netherlands Antillean Guilder (Curaçao)',
    'AOA': 'AOA — Angolan Kwanza (Angola)',
    'ARS': 'ARS — Argentine Peso (Argentina)',
    'AWG': 'AWG — Aruban Florin (Aruba)',
    'AZN': 'AZN — Azerbaijani Manat (Azerbaijan)',
    'BAM': 'BAM — Bosnia-Herzegovina Mark (Bosnia)',
    'BBD': 'BBD — Barbadian Dollar (Barbados)',
    'BDT': 'BDT — Bangladeshi Taka (Bangladesh)',
    'BGN': 'BGN — Bulgarian Lev (Bulgaria)',
    'BHD': 'BHD — Bahraini Dinar (Bahrain)',
    'BIF': 'BIF — Burundian Franc (Burundi)',
    'BMD': 'BMD — Bermudian Dollar (Bermuda)',
    'BOB': 'BOB — Bolivian Boliviano (Bolivia)',
    'BRL': 'BRL — Brazilian Real (Brazil)',
    'BSD': 'BSD — Bahamian Dollar (Bahamas)',
    'BTN': 'BTN — Bhutanese Ngultrum (Bhutan)',
    'BWP': 'BWP — Botswanan Pula (Botswana)',
    'BYN': 'BYN — Belarusian Ruble (Belarus)',
    'BZD': 'BZD — Belize Dollar (Belize)',
    'CDF': 'CDF — Congolese Franc (DR Congo)',
    'CLP': 'CLP — Chilean Peso (Chile)',
    'COP': 'COP — Colombian Peso (Colombia)',
    'CRC': 'CRC — Costa Rican Colón (Costa Rica)',
    'CUP': 'CUP — Cuban Peso (Cuba)',
    'CVE': 'CVE — Cape Verdean Escudo (Cape Verde)',
    'CZK': 'CZK — Czech Koruna (Czech Republic)',
    'DJF': 'DJF — Djiboutian Franc (Djibouti)',
    'DKK': 'DKK — Danish Krone (Denmark)',
    'DOP': 'DOP — Dominican Peso (Dominican Republic)',
    'DZD': 'DZD — Algerian Dinar (Algeria)',
    'EGP': 'EGP — Egyptian Pound (Egypt)',
    'ERN': 'ERN — Eritrean Nakfa (Eritrea)',
    'ETB': 'ETB — Ethiopian Birr (Ethiopia)',
    'FJD': 'FJD — Fijian Dollar (Fiji)',
    'FKP': 'FKP — Falkland Islands Pound (Falkland Islands)',
    'FOK': 'FOK — Faroese Króna (Faroe Islands)',
    'GEL': 'GEL — Georgian Lari (Georgia)',
    'GGP': 'GGP — Guernsey Pound (Guernsey)',
    'GHS': 'GHS — Ghanaian Cedi (Ghana)',
    'GIP': 'GIP — Gibraltar Pound (Gibraltar)',
    'GMD': 'GMD — Gambian Dalasi (Gambia)',
    'GNF': 'GNF — Guinean Franc (Guinea)',
    'GTQ': 'GTQ — Guatemalan Quetzal (Guatemala)',
    'GYD': 'GYD — Guyanaese Dollar (Guyana)',
    'HKD': 'HKD — Hong Kong Dollar (Hong Kong)',
    'HNL': 'HNL — Honduran Lempira (Honduras)',
    'HRK': 'HRK — Croatian Kuna (Croatia)',
    'HTG': 'HTG — Haitian Gourde (Haiti)',
    'HUF': 'HUF — Hungarian Forint (Hungary)',
    'ILS': 'ILS — Israeli Shekel (Israel)',
    'IMP': 'IMP — Manx Pound (Isle of Man)',
    'IQD': 'IQD — Iraqi Dinar (Iraq)',
    'IRR': 'IRR — Iranian Rial (Iran)',
    'ISK': 'ISK — Icelandic Króna (Iceland)',
    'JEP': 'JEP — Jersey Pound (Jersey)',
    'JMD': 'JMD — Jamaican Dollar (Jamaica)',
    'JOD': 'JOD — Jordanian Dinar (Jordan)',
    'KES': 'KES — Kenyan Shilling (Kenya)',
    'KGS': 'KGS — Kyrgyzstani Som (Kyrgyzstan)',
    'KHR': 'KHR — Cambodian Riel (Cambodia)',
    'KID': 'KID — Kiribati Dollar (Kiribati)',
    'KMF': 'KMF — Comorian Franc (Comoros)',
    'KWD': 'KWD — Kuwaiti Dinar (Kuwait)',
    'KYD': 'KYD — Cayman Islands Dollar (Cayman Islands)',
    'KZT': 'KZT — Kazakhstani Tenge (Kazakhstan)',
    'LAK': 'LAK — Lao Kip (Laos)',
    'LBP': 'LBP — Lebanese Pound (Lebanon)',
    'LKR': 'LKR — Sri Lankan Rupee (Sri Lanka)',
    'LRD': 'LRD — Liberian Dollar (Liberia)',
    'LSL': 'LSL — Lesotho Loti (Lesotho)',
    'LYD': 'LYD — Libyan Dinar (Libya)',
    'MAD': 'MAD — Moroccan Dirham (Morocco)',
    'MDL': 'MDL — Moldovan Leu (Moldova)',
    'MGA': 'MGA — Malagasy Ariary (Madagascar)',
    'MKD': 'MKD — Macedonian Denar (North Macedonia)',
    'MMK': 'MMK — Myanmar Kyat (Myanmar)',
    'MNT': 'MNT — Mongolian Tugrik (Mongolia)',
    'MOP': 'MOP — Macanese Pataca (Macau)',
    'MRU': 'MRU — Mauritanian Ouguiya (Mauritania)',
    'MUR': 'MUR — Mauritian Rupee (Mauritius)',
    'MVR': 'MVR — Maldivian Rufiyaa (Maldives)',
    'MWK': 'MWK — Malawian Kwacha (Malawi)',
    'MXN': 'MXN — Mexican Peso (Mexico)',
    'MZN': 'MZN — Mozambican Metical (Mozambique)',
    'NAD': 'NAD — Namibian Dollar (Namibia)',
    'NGN': 'NGN — Nigerian Naira (Nigeria)',
    'NIO': 'NIO — Nicaraguan Córdoba (Nicaragua)',
    'NOK': 'NOK — Norwegian Krone (Norway)',
    'NPR': 'NPR — Nepalese Rupee (Nepal)',
    'NZD': 'NZD — New Zealand Dollar (New Zealand)',
    'OMR': 'OMR — Omani Rial (Oman)',
    'PAB': 'PAB — Panamanian Balboa (Panama)',
    'PEN': 'PEN — Peruvian Sol (Peru)',
    'PGK': 'PGK — Papua New Guinean Kina (Papua New Guinea)',
    'PHP': 'PHP — Philippine Peso (Philippines)',
    'PKR': 'PKR — Pakistani Rupee (Pakistan)',
    'PLN': 'PLN — Polish Zloty (Poland)',
    'PYG': 'PYG — Paraguayan Guarani (Paraguay)',
    'QAR': 'QAR — Qatari Riyal (Qatar)',
    'RON': 'RON — Romanian Leu (Romania)',
    'RSD': 'RSD — Serbian Dinar (Serbia)',
    'RUB': 'RUB — Russian Ruble (Russia)',
    'RWF': 'RWF — Rwandan Franc (Rwanda)',
    'SDG': 'SDG — Sudanese Pound (Sudan)',
    'SEK': 'SEK — Swedish Krona (Sweden)',
    'SHP': 'SHP — Saint Helena Pound (Saint Helena)',
    'SLL': 'SLL — Sierra Leonean Leone (Sierra Leone)',
    'SOS': 'SOS — Somali Shilling (Somalia)',
    'SRD': 'SRD — Surinamese Dollar (Suriname)',
    'SSP': 'SSP — South Sudanese Pound (South Sudan)',
    'STN': 'STN — São Tomé and Príncipe Dobra (São Tomé)',
    'SYP': 'SYP — Syrian Pound (Syria)',
    'SZL': 'SZL — Swazi Lilangeni (Eswatini)',
    'TJS': 'TJS — Tajikistani Somoni (Tajikistan)',
    'TMT': 'TMT — Turkmen Manat (Turkmenistan)',
    'TND': 'TND — Tunisian Dinar (Tunisia)',
    'TOP': 'TOP — Tongan Paʻanga (Tonga)',
    'TRY': 'TRY — Turkish Lira (Turkey)',
    'TTD': 'TTD — Trinidad & Tobago Dollar (Trinidad & Tobago)',
    'TVD': 'TVD — Tuvaluan Dollar (Tuvalu)',
    'TWD': 'TWD — New Taiwan Dollar (Taiwan)',
    'TZS': 'TZS — Tanzanian Shilling (Tanzania)',
    'UAH': 'UAH — Ukrainian Hryvnia (Ukraine)',
    'UGX': 'UGX — Ugandan Shilling (Uganda)',
    'UYU': 'UYU — Uruguayan Peso (Uruguay)',
    'UZS': 'UZS — Uzbekistani Som (Uzbekistan)',
    'VES': 'VES — Venezuelan Bolívar (Venezuela)',
    'WST': 'WST — Samoan Tala (Samoa)',
    'XAF': 'XAF — Central African CFA Franc (CEMAC)',
    'XCD': 'XCD — East Caribbean Dollar (OECS)',
    'XOF': 'XOF — West African CFA Franc (West Africa)',
    'XPF': 'XPF — CFP Franc (French Pacific)',
    'YER': 'YER — Yemeni Rial (Yemen)',
    'ZAR': 'ZAR — South African Rand (South Africa)',
    'ZMW': 'ZMW — Zambian Kwacha (Zambia)',
    'ZWL': 'ZWL — Zimbabwean Dollar (Zimbabwe)',
  };

  /// Returns display label for a currency code, or just the code if unknown.
  static String display(String code) {
    return _names[code.toUpperCase()] ?? code.toUpperCase();
  }

  /// Returns the short label (code only) — same as before, for compact contexts.
  static String code(String code) => code.toUpperCase();
}